import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  page: { flexGrow: 1, backgroundColor: "#f0f2f6", alignItems: "center", justifyContent: "center", padding: 20 },
  card: { width: "100%", borderRadius: 24, padding: 24, backgroundColor: "rgba(255,255,255,0.9)" },
  title: { fontSize: 26, fontWeight: "800", textAlign: "center", marginBottom: 4 },
  subtitle: { textAlign: "center", color: "#666", marginBottom: 16 },
  imageBox: { width: "100%", height: 220, backgroundColor: "#e5e7eb", borderRadius: 16, alignItems: "center", justifyContent: "center", marginBottom: 20, overflow: "hidden" },
  image: { width: "100%", height: "100%" },
  imageText: { color: "#444", fontSize: 16, fontWeight: "600" },
  loadingOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.4)", alignItems: "center", justifyContent: "center" },
  loadingText: { marginTop: 10, color: "white", fontWeight: "600" },
  formGroup: { marginBottom: 12 },
  label: { marginBottom: 6, fontWeight: "600" },
  chipContainer: { flexDirection: "row", marginVertical: 6 },
  chip: { paddingVertical: 6, paddingHorizontal: 14, backgroundColor: "#f0f0f0", borderRadius: 20, marginRight: 10 },
  chipSelected: { backgroundColor: "#616980ff" },
  chipText: { color: "#444", fontWeight: "500" },
  chipTextSelected: { color: "white", fontWeight: "700" },
  input: { backgroundColor: "#fff", borderRadius: 12, borderWidth: 1, borderColor: "#ddd", padding: 12, fontSize: 15 },
  noteInput: { minHeight: 80, textAlignVertical: "top" },
  errorInput: { borderColor: "#ef4444" },
  saveButton: { marginTop: 15, paddingVertical: 16, borderRadius: 14, alignItems: "center" },
  saveText: { color: "white", fontSize: 16, fontWeight: "700", letterSpacing: 0.5 },
});