name: Expo CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: TypeScript check
        run: npx tsc --noEmit
      - name: ESLint check
        run: npx eslint . --ext .ts,.tsx,.js,.jsx
        continue-on-error: true
      - name: Run tests
        run: npm test --if-present
